module.exports = {
    OK: 200,
    VALIDATION_ERROR: 400,
    ENTITY_DUPLICATION_ERROR: 409,
    UNAUTHORIZED_RESOURCE_ERROR: 403,
    INTERNAL_SERVER_ERROR: 500,
    ENTITY_NOT_FOUND_ERROR: 404
};

