module.exports = {
    RESPONSE_STATUS: {
        VALIDATION_ERROR: 400,
        ENTITY_DUPLICATION_ERROR: 403,
        ENTITY_NOT_FOUND_ERROR: 404,
        INTERNAL_SERVER_ERROR: 500,
        ENTITY_CREATED: 201,
        ENTITY_DELETED: 204,
        UNAUTHORIZED_ERROR: 401
    }
};
